package service

// ToolDefinitionsJSON 定时任务使用的工具定义JSON
// 从示例文件 docs/定时对话参数.txt 中提取（完整格式）
const ToolDefinitionsJSON = `[
{"name":"str-replace-editor","description":"Tool for editing existing files.","input_schema_json":"{\"type\":\"object\",\"properties\":{\"command\":{\"type\":\"string\",\"enum\":[\"str_replace\",\"insert\"],\"description\":\"The commands to run.\"},\"path\":{\"description\":\"Full path to file.\",\"type\":\"string\"},\"instruction_reminder\":{\"description\":\"Reminder string.\",\"type\":\"string\"}},\"required\":[\"command\",\"path\",\"instruction_reminder\"]}","tool_safety":1},
{"name":"open-browser","description":"Open a URL in the default browser.","input_schema_json":"{\"type\":\"object\",\"properties\":{\"url\":{\"type\":\"string\",\"description\":\"The URL to open.\"}},\"required\":[\"url\"]}","tool_safety":1},
{"name":"diagnostics","description":"Get issues from the IDE.","input_schema_json":"{\"type\":\"object\",\"properties\":{\"paths\":{\"type\":\"array\",\"items\":{\"type\":\"string\"},\"description\":\"File paths.\"}},\"required\":[\"paths\"]}","tool_safety":1},
{"name":"read-terminal","description":"Read output from the VSCode terminal.","input_schema_json":"{\"type\":\"object\",\"properties\":{\"only_selected\":{\"type\":\"boolean\",\"description\":\"Read only selected text.\"}},\"required\":[]}","tool_safety":1},
{"name":"git-commit-retrieval","description":"Context engine with git commit history.","input_schema_json":"{\"type\":\"object\",\"properties\":{\"information_request\":{\"type\":\"string\",\"description\":\"Information request.\"}},\"required\":[\"information_request\"]}","tool_safety":1},
{"name":"launch-process","description":"Launch a new process with a shell command.","input_schema_json":"{\"type\":\"object\",\"properties\":{\"command\":{\"type\":\"string\"},\"wait\":{\"type\":\"boolean\"},\"max_wait_seconds\":{\"type\":\"number\"},\"cwd\":{\"type\":\"string\"}},\"required\":[\"command\",\"wait\",\"max_wait_seconds\",\"cwd\"]}","tool_safety":2},
{"name":"kill-process","description":"Kill a process by its terminal ID.","input_schema_json":"{\"type\":\"object\",\"properties\":{\"terminal_id\":{\"type\":\"integer\",\"description\":\"Terminal ID.\"}},\"required\":[\"terminal_id\"]}","tool_safety":1},
{"name":"read-process","description":"Read output from a terminal.","input_schema_json":"{\"type\":\"object\",\"properties\":{\"terminal_id\":{\"type\":\"integer\"},\"wait\":{\"type\":\"boolean\"},\"max_wait_seconds\":{\"type\":\"number\"}},\"required\":[\"terminal_id\",\"wait\",\"max_wait_seconds\"]}","tool_safety":1},
{"name":"write-process","description":"Write input to a terminal.","input_schema_json":"{\"type\":\"object\",\"properties\":{\"terminal_id\":{\"type\":\"integer\"},\"input_text\":{\"type\":\"string\"}},\"required\":[\"terminal_id\",\"input_text\"]}","tool_safety":1},
{"name":"list-processes","description":"List all known terminals.","input_schema_json":"{\"type\":\"object\",\"properties\":{},\"required\":[]}","tool_safety":1},
{"name":"web-search","description":"Search the web for information.","input_schema_json":"{\"type\":\"object\",\"properties\":{\"query\":{\"type\":\"string\"},\"num_results\":{\"type\":\"integer\",\"default\":5}},\"required\":[\"query\"]}","tool_safety":0},
{"name":"web-fetch","description":"Fetches data from a webpage.","input_schema_json":"{\"type\":\"object\",\"properties\":{\"url\":{\"type\":\"string\",\"description\":\"The URL to fetch.\"}},\"required\":[\"url\"]}","tool_safety":0},
{"name":"codebase-retrieval","description":"Augment context engine.","input_schema_json":"{\"type\":\"object\",\"properties\":{\"information_request\":{\"type\":\"string\",\"description\":\"Information request.\"}},\"required\":[\"information_request\"]}","tool_safety":1},
{"name":"remove-files","description":"Remove files from workspace.","input_schema_json":"{\"type\":\"object\",\"properties\":{\"file_paths\":{\"type\":\"array\",\"items\":{\"type\":\"string\"}}},\"required\":[\"file_paths\"]}","tool_safety":1},
{"name":"save-file","description":"Save a new file.","input_schema_json":"{\"type\":\"object\",\"properties\":{\"instructions_reminder\":{\"type\":\"string\"},\"path\":{\"type\":\"string\"},\"file_content\":{\"type\":\"string\"},\"add_last_line_newline\":{\"type\":\"boolean\"}},\"required\":[\"instructions_reminder\",\"path\",\"file_content\"]}","tool_safety":1},
{"name":"view_tasklist","description":"View the current task list.","input_schema_json":"{\"type\":\"object\",\"properties\":{},\"required\":[]}","tool_safety":1},
{"name":"reorganize_tasklist","description":"Reorganize the task list structure.","input_schema_json":"{\"type\":\"object\",\"properties\":{\"markdown\":{\"type\":\"string\"}},\"required\":[\"markdown\"]}","tool_safety":1},
{"name":"update_tasks","description":"Update tasks properties.","input_schema_json":"{\"type\":\"object\",\"properties\":{\"tasks\":{\"type\":\"array\",\"items\":{\"type\":\"object\"}}},\"required\":[\"tasks\"]}","tool_safety":1},
{"name":"add_tasks","description":"Add new tasks to the task list.","input_schema_json":"{\"type\":\"object\",\"properties\":{\"tasks\":{\"type\":\"array\",\"items\":{\"type\":\"object\"}}},\"required\":[\"tasks\"]}","tool_safety":1},
{"name":"remember","description":"Remember information for long-term.","input_schema_json":"{\"type\":\"object\",\"properties\":{\"memory\":{\"type\":\"string\",\"description\":\"The memory to remember.\"}},\"required\":[\"memory\"]}","tool_safety":1},
{"name":"render-mermaid","description":"Render a Mermaid diagram.","input_schema_json":"{\"type\":\"object\",\"properties\":{\"diagram_definition\":{\"type\":\"string\"},\"title\":{\"type\":\"string\",\"default\":\"Mermaid Diagram\"}},\"required\":[\"diagram_definition\"]}","tool_safety":1},
{"name":"view-range-untruncated","description":"View a specific range of lines.","input_schema_json":"{\"type\":\"object\",\"properties\":{\"reference_id\":{\"type\":\"string\"},\"start_line\":{\"type\":\"integer\"},\"end_line\":{\"type\":\"integer\"}},\"required\":[\"reference_id\",\"start_line\",\"end_line\"]}","tool_safety":1},
{"name":"search-untruncated","description":"Search for a term within content.","input_schema_json":"{\"type\":\"object\",\"properties\":{\"reference_id\":{\"type\":\"string\"},\"search_term\":{\"type\":\"string\"},\"context_lines\":{\"type\":\"integer\"}},\"required\":[\"reference_id\",\"search_term\"]}","tool_safety":1},
{"name":"apply_patch","description":"Apply a diff/patch against a file.","input_schema_json":"{\"type\":\"object\",\"properties\":{\"input\":{\"type\":\"string\",\"description\":\"The apply_patch command.\"}},\"required\":[\"input\"]}","tool_safety":1},
{"name":"view","description":"View files and directories.","input_schema_json":"{\"type\":\"object\",\"properties\":{\"type\":{\"type\":\"string\",\"enum\":[\"file\",\"directory\"],\"default\":\"file\"},\"path\":{\"type\":\"string\"},\"view_range\":{\"type\":\"array\",\"items\":{\"type\":\"integer\"}},\"search_query_regex\":{\"type\":\"string\"},\"case_sensitive\":{\"type\":\"boolean\",\"default\":false}},\"required\":[\"path\"]}","tool_safety":1}
]`
